// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/GenericCommand.proto

package com.hoymiles.infrastructure.protos;

public final class GenericCommand {
  private GenericCommand() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GenericCommandResDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hoymiles.GenericCommandResDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes ymdHms = 1;</code>
     * @return Whether the ymdHms field is set.
     */
    boolean hasYmdHms();
    /**
     * <code>required bytes ymdHms = 1;</code>
     * @return The ymdHms.
     */
    com.google.protobuf.ByteString getYmdHms();

    /**
     * <code>optional int32 packageNow = 2;</code>
     * @return Whether the packageNow field is set.
     */
    boolean hasPackageNow();
    /**
     * <code>optional int32 packageNow = 2;</code>
     * @return The packageNow.
     */
    int getPackageNow();

    /**
     * <code>optional int32 errCode = 3;</code>
     * @return Whether the errCode field is set.
     */
    boolean hasErrCode();
    /**
     * <code>optional int32 errCode = 3;</code>
     * @return The errCode.
     */
    int getErrCode();

    /**
     * <code>required int32 offset = 4;</code>
     * @return Whether the offset field is set.
     */
    boolean hasOffset();
    /**
     * <code>required int32 offset = 4;</code>
     * @return The offset.
     */
    int getOffset();

    /**
     * <code>required int32 time = 5;</code>
     * @return Whether the time field is set.
     */
    boolean hasTime();
    /**
     * <code>required int32 time = 5;</code>
     * @return The time.
     */
    int getTime();
  }
  /**
   * <pre>
   **
   *484d230b01fd77b100280a13323032322d30332d31322031363a31373a313620901c288caeb19106
   *request, msgId=8971, 8972
   *payload: 0A13323032322D30332D31322031363A31373A313620901C288CAEB19106
   *Field #1: 0A String Length = 19, Hex = 13, UTF8 = "2022-03-12 16:17:16"
   *Field #4: 20 Varint Value = 3600, Hex = 90-1C
   *Field #5: 28 Varint Value = 1647073036, Hex = 8C-AE-B1-91-06
   * </pre>
   *
   * Protobuf type {@code hoymiles.GenericCommandResDTO}
   */
  public static final class GenericCommandResDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:hoymiles.GenericCommandResDTO)
      GenericCommandResDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GenericCommandResDTO.newBuilder() to construct.
    private GenericCommandResDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GenericCommandResDTO() {
      ymdHms_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GenericCommandResDTO();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GenericCommandResDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              ymdHms_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              packageNow_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              errCode_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              offset_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              time_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hoymiles.infrastructure.protos.GenericCommand.internal_static_hoymiles_GenericCommandResDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hoymiles.infrastructure.protos.GenericCommand.internal_static_hoymiles_GenericCommandResDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO.class, com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO.Builder.class);
    }

    private int bitField0_;
    public static final int YMDHMS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString ymdHms_;
    /**
     * <code>required bytes ymdHms = 1;</code>
     * @return Whether the ymdHms field is set.
     */
    @java.lang.Override
    public boolean hasYmdHms() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required bytes ymdHms = 1;</code>
     * @return The ymdHms.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getYmdHms() {
      return ymdHms_;
    }

    public static final int PACKAGENOW_FIELD_NUMBER = 2;
    private int packageNow_;
    /**
     * <code>optional int32 packageNow = 2;</code>
     * @return Whether the packageNow field is set.
     */
    @java.lang.Override
    public boolean hasPackageNow() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 packageNow = 2;</code>
     * @return The packageNow.
     */
    @java.lang.Override
    public int getPackageNow() {
      return packageNow_;
    }

    public static final int ERRCODE_FIELD_NUMBER = 3;
    private int errCode_;
    /**
     * <code>optional int32 errCode = 3;</code>
     * @return Whether the errCode field is set.
     */
    @java.lang.Override
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 errCode = 3;</code>
     * @return The errCode.
     */
    @java.lang.Override
    public int getErrCode() {
      return errCode_;
    }

    public static final int OFFSET_FIELD_NUMBER = 4;
    private int offset_;
    /**
     * <code>required int32 offset = 4;</code>
     * @return Whether the offset field is set.
     */
    @java.lang.Override
    public boolean hasOffset() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int32 offset = 4;</code>
     * @return The offset.
     */
    @java.lang.Override
    public int getOffset() {
      return offset_;
    }

    public static final int TIME_FIELD_NUMBER = 5;
    private int time_;
    /**
     * <code>required int32 time = 5;</code>
     * @return Whether the time field is set.
     */
    @java.lang.Override
    public boolean hasTime() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required int32 time = 5;</code>
     * @return The time.
     */
    @java.lang.Override
    public int getTime() {
      return time_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasYmdHms()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOffset()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, ymdHms_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, packageNow_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, offset_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, time_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, ymdHms_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, packageNow_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, offset_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, time_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO)) {
        return super.equals(obj);
      }
      com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO other = (com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO) obj;

      if (hasYmdHms() != other.hasYmdHms()) return false;
      if (hasYmdHms()) {
        if (!getYmdHms()
            .equals(other.getYmdHms())) return false;
      }
      if (hasPackageNow() != other.hasPackageNow()) return false;
      if (hasPackageNow()) {
        if (getPackageNow()
            != other.getPackageNow()) return false;
      }
      if (hasErrCode() != other.hasErrCode()) return false;
      if (hasErrCode()) {
        if (getErrCode()
            != other.getErrCode()) return false;
      }
      if (hasOffset() != other.hasOffset()) return false;
      if (hasOffset()) {
        if (getOffset()
            != other.getOffset()) return false;
      }
      if (hasTime() != other.hasTime()) return false;
      if (hasTime()) {
        if (getTime()
            != other.getTime()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasYmdHms()) {
        hash = (37 * hash) + YMDHMS_FIELD_NUMBER;
        hash = (53 * hash) + getYmdHms().hashCode();
      }
      if (hasPackageNow()) {
        hash = (37 * hash) + PACKAGENOW_FIELD_NUMBER;
        hash = (53 * hash) + getPackageNow();
      }
      if (hasErrCode()) {
        hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
        hash = (53 * hash) + getErrCode();
      }
      if (hasOffset()) {
        hash = (37 * hash) + OFFSET_FIELD_NUMBER;
        hash = (53 * hash) + getOffset();
      }
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     *484d230b01fd77b100280a13323032322d30332d31322031363a31373a313620901c288caeb19106
     *request, msgId=8971, 8972
     *payload: 0A13323032322D30332D31322031363A31373A313620901C288CAEB19106
     *Field #1: 0A String Length = 19, Hex = 13, UTF8 = "2022-03-12 16:17:16"
     *Field #4: 20 Varint Value = 3600, Hex = 90-1C
     *Field #5: 28 Varint Value = 1647073036, Hex = 8C-AE-B1-91-06
     * </pre>
     *
     * Protobuf type {@code hoymiles.GenericCommandResDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hoymiles.GenericCommandResDTO)
        com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hoymiles.infrastructure.protos.GenericCommand.internal_static_hoymiles_GenericCommandResDTO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hoymiles.infrastructure.protos.GenericCommand.internal_static_hoymiles_GenericCommandResDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO.class, com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO.Builder.class);
      }

      // Construct using com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ymdHms_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        packageNow_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        errCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        offset_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        time_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hoymiles.infrastructure.protos.GenericCommand.internal_static_hoymiles_GenericCommandResDTO_descriptor;
      }

      @java.lang.Override
      public com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO getDefaultInstanceForType() {
        return com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO.getDefaultInstance();
      }

      @java.lang.Override
      public com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO build() {
        com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO buildPartial() {
        com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO result = new com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ymdHms_ = ymdHms_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.packageNow_ = packageNow_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.errCode_ = errCode_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.offset_ = offset_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.time_ = time_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO) {
          return mergeFrom((com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO other) {
        if (other == com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO.getDefaultInstance()) return this;
        if (other.hasYmdHms()) {
          setYmdHms(other.getYmdHms());
        }
        if (other.hasPackageNow()) {
          setPackageNow(other.getPackageNow());
        }
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasOffset()) {
          setOffset(other.getOffset());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasYmdHms()) {
          return false;
        }
        if (!hasOffset()) {
          return false;
        }
        if (!hasTime()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString ymdHms_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes ymdHms = 1;</code>
       * @return Whether the ymdHms field is set.
       */
      @java.lang.Override
      public boolean hasYmdHms() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required bytes ymdHms = 1;</code>
       * @return The ymdHms.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getYmdHms() {
        return ymdHms_;
      }
      /**
       * <code>required bytes ymdHms = 1;</code>
       * @param value The ymdHms to set.
       * @return This builder for chaining.
       */
      public Builder setYmdHms(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ymdHms_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes ymdHms = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearYmdHms() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ymdHms_ = getDefaultInstance().getYmdHms();
        onChanged();
        return this;
      }

      private int packageNow_ ;
      /**
       * <code>optional int32 packageNow = 2;</code>
       * @return Whether the packageNow field is set.
       */
      @java.lang.Override
      public boolean hasPackageNow() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 packageNow = 2;</code>
       * @return The packageNow.
       */
      @java.lang.Override
      public int getPackageNow() {
        return packageNow_;
      }
      /**
       * <code>optional int32 packageNow = 2;</code>
       * @param value The packageNow to set.
       * @return This builder for chaining.
       */
      public Builder setPackageNow(int value) {
        bitField0_ |= 0x00000002;
        packageNow_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 packageNow = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPackageNow() {
        bitField0_ = (bitField0_ & ~0x00000002);
        packageNow_ = 0;
        onChanged();
        return this;
      }

      private int errCode_ ;
      /**
       * <code>optional int32 errCode = 3;</code>
       * @return Whether the errCode field is set.
       */
      @java.lang.Override
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       * @return The errCode.
       */
      @java.lang.Override
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       * @param value The errCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrCode(int value) {
        bitField0_ |= 0x00000004;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errCode_ = 0;
        onChanged();
        return this;
      }

      private int offset_ ;
      /**
       * <code>required int32 offset = 4;</code>
       * @return Whether the offset field is set.
       */
      @java.lang.Override
      public boolean hasOffset() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required int32 offset = 4;</code>
       * @return The offset.
       */
      @java.lang.Override
      public int getOffset() {
        return offset_;
      }
      /**
       * <code>required int32 offset = 4;</code>
       * @param value The offset to set.
       * @return This builder for chaining.
       */
      public Builder setOffset(int value) {
        bitField0_ |= 0x00000008;
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 offset = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearOffset() {
        bitField0_ = (bitField0_ & ~0x00000008);
        offset_ = 0;
        onChanged();
        return this;
      }

      private int time_ ;
      /**
       * <code>required int32 time = 5;</code>
       * @return Whether the time field is set.
       */
      @java.lang.Override
      public boolean hasTime() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required int32 time = 5;</code>
       * @return The time.
       */
      @java.lang.Override
      public int getTime() {
        return time_;
      }
      /**
       * <code>required int32 time = 5;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(int value) {
        bitField0_ |= 0x00000010;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 time = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        time_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:hoymiles.GenericCommandResDTO)
    }

    // @@protoc_insertion_point(class_scope:hoymiles.GenericCommandResDTO)
    private static final com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO();
    }

    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GenericCommandResDTO>
        PARSER = new com.google.protobuf.AbstractParser<GenericCommandResDTO>() {
      @java.lang.Override
      public GenericCommandResDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GenericCommandResDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GenericCommandResDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenericCommandResDTO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GenericCommandResDTO2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:hoymiles.GenericCommandResDTO2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 offset = 1;</code>
     * @return Whether the offset field is set.
     */
    boolean hasOffset();
    /**
     * <code>required int32 offset = 1;</code>
     * @return The offset.
     */
    int getOffset();

    /**
     * <code>required int32 time = 2;</code>
     * @return Whether the time field is set.
     */
    boolean hasTime();
    /**
     * <code>required int32 time = 2;</code>
     * @return The time.
     */
    int getTime();

    /**
     * <code>required bytes ymdHms = 3;</code>
     * @return Whether the ymdHms field is set.
     */
    boolean hasYmdHms();
    /**
     * <code>required bytes ymdHms = 3;</code>
     * @return The ymdHms.
     */
    com.google.protobuf.ByteString getYmdHms();
  }
  /**
   * <pre>
   **
   *484d23020326fa57002808901c10ebffbc91061a13323032322d30332d31342032313a31353a3233
   *request, msgId=8962
   *Field #1: 08 Varint Value = 3600, Hex = 90-1C
   *Field #2: 10 Varint Value = 1647263723, Hex = EB-FF-BC-91-06
   *Field #3: 1A String Length = 19, Hex = 13, UTF8 = "2022-03-14 21:15:23"
   * </pre>
   *
   * Protobuf type {@code hoymiles.GenericCommandResDTO2}
   */
  public static final class GenericCommandResDTO2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:hoymiles.GenericCommandResDTO2)
      GenericCommandResDTO2OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GenericCommandResDTO2.newBuilder() to construct.
    private GenericCommandResDTO2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GenericCommandResDTO2() {
      ymdHms_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GenericCommandResDTO2();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GenericCommandResDTO2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              offset_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              time_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              ymdHms_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hoymiles.infrastructure.protos.GenericCommand.internal_static_hoymiles_GenericCommandResDTO2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hoymiles.infrastructure.protos.GenericCommand.internal_static_hoymiles_GenericCommandResDTO2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2.class, com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2.Builder.class);
    }

    private int bitField0_;
    public static final int OFFSET_FIELD_NUMBER = 1;
    private int offset_;
    /**
     * <code>required int32 offset = 1;</code>
     * @return Whether the offset field is set.
     */
    @java.lang.Override
    public boolean hasOffset() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 offset = 1;</code>
     * @return The offset.
     */
    @java.lang.Override
    public int getOffset() {
      return offset_;
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private int time_;
    /**
     * <code>required int32 time = 2;</code>
     * @return Whether the time field is set.
     */
    @java.lang.Override
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 time = 2;</code>
     * @return The time.
     */
    @java.lang.Override
    public int getTime() {
      return time_;
    }

    public static final int YMDHMS_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString ymdHms_;
    /**
     * <code>required bytes ymdHms = 3;</code>
     * @return Whether the ymdHms field is set.
     */
    @java.lang.Override
    public boolean hasYmdHms() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required bytes ymdHms = 3;</code>
     * @return The ymdHms.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getYmdHms() {
      return ymdHms_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOffset()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasYmdHms()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, offset_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, time_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBytes(3, ymdHms_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, offset_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, time_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, ymdHms_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2)) {
        return super.equals(obj);
      }
      com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 other = (com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2) obj;

      if (hasOffset() != other.hasOffset()) return false;
      if (hasOffset()) {
        if (getOffset()
            != other.getOffset()) return false;
      }
      if (hasTime() != other.hasTime()) return false;
      if (hasTime()) {
        if (getTime()
            != other.getTime()) return false;
      }
      if (hasYmdHms() != other.hasYmdHms()) return false;
      if (hasYmdHms()) {
        if (!getYmdHms()
            .equals(other.getYmdHms())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOffset()) {
        hash = (37 * hash) + OFFSET_FIELD_NUMBER;
        hash = (53 * hash) + getOffset();
      }
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime();
      }
      if (hasYmdHms()) {
        hash = (37 * hash) + YMDHMS_FIELD_NUMBER;
        hash = (53 * hash) + getYmdHms().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     *484d23020326fa57002808901c10ebffbc91061a13323032322d30332d31342032313a31353a3233
     *request, msgId=8962
     *Field #1: 08 Varint Value = 3600, Hex = 90-1C
     *Field #2: 10 Varint Value = 1647263723, Hex = EB-FF-BC-91-06
     *Field #3: 1A String Length = 19, Hex = 13, UTF8 = "2022-03-14 21:15:23"
     * </pre>
     *
     * Protobuf type {@code hoymiles.GenericCommandResDTO2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hoymiles.GenericCommandResDTO2)
        com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hoymiles.infrastructure.protos.GenericCommand.internal_static_hoymiles_GenericCommandResDTO2_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hoymiles.infrastructure.protos.GenericCommand.internal_static_hoymiles_GenericCommandResDTO2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2.class, com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2.Builder.class);
      }

      // Construct using com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        offset_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        ymdHms_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hoymiles.infrastructure.protos.GenericCommand.internal_static_hoymiles_GenericCommandResDTO2_descriptor;
      }

      @java.lang.Override
      public com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 getDefaultInstanceForType() {
        return com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2.getDefaultInstance();
      }

      @java.lang.Override
      public com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 build() {
        com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 buildPartial() {
        com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 result = new com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.offset_ = offset_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.time_ = time_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ymdHms_ = ymdHms_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2) {
          return mergeFrom((com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 other) {
        if (other == com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2.getDefaultInstance()) return this;
        if (other.hasOffset()) {
          setOffset(other.getOffset());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasYmdHms()) {
          setYmdHms(other.getYmdHms());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasOffset()) {
          return false;
        }
        if (!hasTime()) {
          return false;
        }
        if (!hasYmdHms()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int offset_ ;
      /**
       * <code>required int32 offset = 1;</code>
       * @return Whether the offset field is set.
       */
      @java.lang.Override
      public boolean hasOffset() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 offset = 1;</code>
       * @return The offset.
       */
      @java.lang.Override
      public int getOffset() {
        return offset_;
      }
      /**
       * <code>required int32 offset = 1;</code>
       * @param value The offset to set.
       * @return This builder for chaining.
       */
      public Builder setOffset(int value) {
        bitField0_ |= 0x00000001;
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 offset = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOffset() {
        bitField0_ = (bitField0_ & ~0x00000001);
        offset_ = 0;
        onChanged();
        return this;
      }

      private int time_ ;
      /**
       * <code>required int32 time = 2;</code>
       * @return Whether the time field is set.
       */
      @java.lang.Override
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 time = 2;</code>
       * @return The time.
       */
      @java.lang.Override
      public int getTime() {
        return time_;
      }
      /**
       * <code>required int32 time = 2;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(int value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString ymdHms_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes ymdHms = 3;</code>
       * @return Whether the ymdHms field is set.
       */
      @java.lang.Override
      public boolean hasYmdHms() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required bytes ymdHms = 3;</code>
       * @return The ymdHms.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getYmdHms() {
        return ymdHms_;
      }
      /**
       * <code>required bytes ymdHms = 3;</code>
       * @param value The ymdHms to set.
       * @return This builder for chaining.
       */
      public Builder setYmdHms(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ymdHms_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes ymdHms = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearYmdHms() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ymdHms_ = getDefaultInstance().getYmdHms();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:hoymiles.GenericCommandResDTO2)
    }

    // @@protoc_insertion_point(class_scope:hoymiles.GenericCommandResDTO2)
    private static final com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2();
    }

    public static com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GenericCommandResDTO2>
        PARSER = new com.google.protobuf.AbstractParser<GenericCommandResDTO2>() {
      @java.lang.Override
      public GenericCommandResDTO2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GenericCommandResDTO2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GenericCommandResDTO2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenericCommandResDTO2> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hoymiles.infrastructure.protos.GenericCommand.GenericCommandResDTO2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hoymiles_GenericCommandResDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hoymiles_GenericCommandResDTO_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hoymiles_GenericCommandResDTO2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hoymiles_GenericCommandResDTO2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-src/main/resources/proto/GenericComman" +
      "d.proto\022\010hoymiles\"i\n\024GenericCommandResDT" +
      "O\022\016\n\006ymdHms\030\001 \002(\014\022\022\n\npackageNow\030\002 \001(\005\022\017\n" +
      "\007errCode\030\003 \001(\005\022\016\n\006offset\030\004 \002(\005\022\014\n\004time\030\005" +
      " \002(\005\"E\n\025GenericCommandResDTO2\022\016\n\006offset\030" +
      "\001 \002(\005\022\014\n\004time\030\002 \002(\005\022\016\n\006ymdHms\030\003 \002(\014B6\n\"c" +
      "om.hoymiles.infrastructure.protosB\016Gener" +
      "icCommandP\000"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_hoymiles_GenericCommandResDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hoymiles_GenericCommandResDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hoymiles_GenericCommandResDTO_descriptor,
        new java.lang.String[] { "YmdHms", "PackageNow", "ErrCode", "Offset", "Time", });
    internal_static_hoymiles_GenericCommandResDTO2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hoymiles_GenericCommandResDTO2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hoymiles_GenericCommandResDTO2_descriptor,
        new java.lang.String[] { "Offset", "Time", "YmdHms", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
