// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/NetworkInfo.proto

package com.hoymiles.infrastructure.protos;

public final class NetworkInfo {
  private NetworkInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NetworkInfoResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hoymiles.NetworkInfoRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 offset = 1;</code>
     * @return Whether the offset field is set.
     */
    boolean hasOffset();
    /**
     * <code>required int32 offset = 1;</code>
     * @return The offset.
     */
    int getOffset();

    /**
     * <code>required int32 time = 2;</code>
     * @return Whether the time field is set.
     */
    boolean hasTime();
    /**
     * <code>required int32 time = 2;</code>
     * @return The time.
     */
    int getTime();
  }
  /**
   * Protobuf type {@code hoymiles.NetworkInfoRes}
   */
  public static final class NetworkInfoRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:hoymiles.NetworkInfoRes)
      NetworkInfoResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NetworkInfoRes.newBuilder() to construct.
    private NetworkInfoRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NetworkInfoRes() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NetworkInfoRes();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NetworkInfoRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              offset_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              time_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hoymiles.infrastructure.protos.NetworkInfo.internal_static_hoymiles_NetworkInfoRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hoymiles.infrastructure.protos.NetworkInfo.internal_static_hoymiles_NetworkInfoRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes.class, com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes.Builder.class);
    }

    private int bitField0_;
    public static final int OFFSET_FIELD_NUMBER = 1;
    private int offset_;
    /**
     * <code>required int32 offset = 1;</code>
     * @return Whether the offset field is set.
     */
    @java.lang.Override
    public boolean hasOffset() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 offset = 1;</code>
     * @return The offset.
     */
    @java.lang.Override
    public int getOffset() {
      return offset_;
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private int time_;
    /**
     * <code>required int32 time = 2;</code>
     * @return Whether the time field is set.
     */
    @java.lang.Override
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 time = 2;</code>
     * @return The time.
     */
    @java.lang.Override
    public int getTime() {
      return time_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOffset()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, offset_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, time_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, offset_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, time_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes)) {
        return super.equals(obj);
      }
      com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes other = (com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes) obj;

      if (hasOffset() != other.hasOffset()) return false;
      if (hasOffset()) {
        if (getOffset()
            != other.getOffset()) return false;
      }
      if (hasTime() != other.hasTime()) return false;
      if (hasTime()) {
        if (getTime()
            != other.getTime()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOffset()) {
        hash = (37 * hash) + OFFSET_FIELD_NUMBER;
        hash = (53 * hash) + getOffset();
      }
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hoymiles.NetworkInfoRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hoymiles.NetworkInfoRes)
        com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hoymiles.infrastructure.protos.NetworkInfo.internal_static_hoymiles_NetworkInfoRes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hoymiles.infrastructure.protos.NetworkInfo.internal_static_hoymiles_NetworkInfoRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes.class, com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes.Builder.class);
      }

      // Construct using com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        offset_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hoymiles.infrastructure.protos.NetworkInfo.internal_static_hoymiles_NetworkInfoRes_descriptor;
      }

      @java.lang.Override
      public com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes getDefaultInstanceForType() {
        return com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes.getDefaultInstance();
      }

      @java.lang.Override
      public com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes build() {
        com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes buildPartial() {
        com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes result = new com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.offset_ = offset_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.time_ = time_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes) {
          return mergeFrom((com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes other) {
        if (other == com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes.getDefaultInstance()) return this;
        if (other.hasOffset()) {
          setOffset(other.getOffset());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasOffset()) {
          return false;
        }
        if (!hasTime()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int offset_ ;
      /**
       * <code>required int32 offset = 1;</code>
       * @return Whether the offset field is set.
       */
      @java.lang.Override
      public boolean hasOffset() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 offset = 1;</code>
       * @return The offset.
       */
      @java.lang.Override
      public int getOffset() {
        return offset_;
      }
      /**
       * <code>required int32 offset = 1;</code>
       * @param value The offset to set.
       * @return This builder for chaining.
       */
      public Builder setOffset(int value) {
        bitField0_ |= 0x00000001;
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 offset = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOffset() {
        bitField0_ = (bitField0_ & ~0x00000001);
        offset_ = 0;
        onChanged();
        return this;
      }

      private int time_ ;
      /**
       * <code>required int32 time = 2;</code>
       * @return Whether the time field is set.
       */
      @java.lang.Override
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 time = 2;</code>
       * @return The time.
       */
      @java.lang.Override
      public int getTime() {
        return time_;
      }
      /**
       * <code>required int32 time = 2;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(int value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:hoymiles.NetworkInfoRes)
    }

    // @@protoc_insertion_point(class_scope:hoymiles.NetworkInfoRes)
    private static final com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes();
    }

    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NetworkInfoRes>
        PARSER = new com.google.protobuf.AbstractParser<NetworkInfoRes>() {
      @java.lang.Override
      public NetworkInfoRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetworkInfoRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NetworkInfoRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetworkInfoRes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NetworkInfoReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hoymiles.NetworkInfoReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 apSetState = 10;</code>
     * @return Whether the apSetState field is set.
     */
    boolean hasApSetState();
    /**
     * <code>optional int32 apSetState = 10;</code>
     * @return The apSetState.
     */
    int getApSetState();

    /**
     * <code>optional int32 csq = 8;</code>
     * @return Whether the csq field is set.
     */
    boolean hasCsq();
    /**
     * <code>optional int32 csq = 8;</code>
     * @return The csq.
     */
    int getCsq();

    /**
     * <code>required bytes dtuSn = 1;</code>
     * @return Whether the dtuSn field is set.
     */
    boolean hasDtuSn();
    /**
     * <code>required bytes dtuSn = 1;</code>
     * @return The dtuSn.
     */
    com.google.protobuf.ByteString getDtuSn();

    /**
     * <code>optional int32 netSetMod = 3;</code>
     * @return Whether the netSetMod field is set.
     */
    boolean hasNetSetMod();
    /**
     * <code>optional int32 netSetMod = 3;</code>
     * @return The netSetMod.
     */
    int getNetSetMod();

    /**
     * <code>optional int32 netSetState = 5;</code>
     * @return Whether the netSetState field is set.
     */
    boolean hasNetSetState();
    /**
     * <code>optional int32 netSetState = 5;</code>
     * @return The netSetState.
     */
    int getNetSetState();

    /**
     * <code>optional int32 netSetTime = 4;</code>
     * @return Whether the netSetTime field is set.
     */
    boolean hasNetSetTime();
    /**
     * <code>optional int32 netSetTime = 4;</code>
     * @return The netSetTime.
     */
    int getNetSetTime();

    /**
     * <code>optional int32 netWorkMod = 6;</code>
     * @return Whether the netWorkMod field is set.
     */
    boolean hasNetWorkMod();
    /**
     * <code>optional int32 netWorkMod = 6;</code>
     * @return The netWorkMod.
     */
    int getNetWorkMod();

    /**
     * <code>optional int32 netWorkState = 9;</code>
     * @return Whether the netWorkState field is set.
     */
    boolean hasNetWorkState();
    /**
     * <code>optional int32 netWorkState = 9;</code>
     * @return The netWorkState.
     */
    int getNetWorkState();

    /**
     * <code>optional int32 netWorkTime = 7;</code>
     * @return Whether the netWorkTime field is set.
     */
    boolean hasNetWorkTime();
    /**
     * <code>optional int32 netWorkTime = 7;</code>
     * @return The netWorkTime.
     */
    int getNetWorkTime();

    /**
     * <code>optional int32 time = 2;</code>
     * @return Whether the time field is set.
     */
    boolean hasTime();
    /**
     * <code>optional int32 time = 2;</code>
     * @return The time.
     */
    int getTime();
  }
  /**
   * Protobuf type {@code hoymiles.NetworkInfoReq}
   */
  public static final class NetworkInfoReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:hoymiles.NetworkInfoReq)
      NetworkInfoReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NetworkInfoReq.newBuilder() to construct.
    private NetworkInfoReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NetworkInfoReq() {
      dtuSn_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NetworkInfoReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NetworkInfoReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000004;
              dtuSn_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000200;
              time_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000008;
              netSetMod_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000020;
              netSetTime_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              netSetState_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000040;
              netWorkMod_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000100;
              netWorkTime_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000002;
              csq_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000080;
              netWorkState_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000001;
              apSetState_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hoymiles.infrastructure.protos.NetworkInfo.internal_static_hoymiles_NetworkInfoReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hoymiles.infrastructure.protos.NetworkInfo.internal_static_hoymiles_NetworkInfoReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq.class, com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq.Builder.class);
    }

    private int bitField0_;
    public static final int APSETSTATE_FIELD_NUMBER = 10;
    private int apSetState_;
    /**
     * <code>optional int32 apSetState = 10;</code>
     * @return Whether the apSetState field is set.
     */
    @java.lang.Override
    public boolean hasApSetState() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 apSetState = 10;</code>
     * @return The apSetState.
     */
    @java.lang.Override
    public int getApSetState() {
      return apSetState_;
    }

    public static final int CSQ_FIELD_NUMBER = 8;
    private int csq_;
    /**
     * <code>optional int32 csq = 8;</code>
     * @return Whether the csq field is set.
     */
    @java.lang.Override
    public boolean hasCsq() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 csq = 8;</code>
     * @return The csq.
     */
    @java.lang.Override
    public int getCsq() {
      return csq_;
    }

    public static final int DTUSN_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString dtuSn_;
    /**
     * <code>required bytes dtuSn = 1;</code>
     * @return Whether the dtuSn field is set.
     */
    @java.lang.Override
    public boolean hasDtuSn() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required bytes dtuSn = 1;</code>
     * @return The dtuSn.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDtuSn() {
      return dtuSn_;
    }

    public static final int NETSETMOD_FIELD_NUMBER = 3;
    private int netSetMod_;
    /**
     * <code>optional int32 netSetMod = 3;</code>
     * @return Whether the netSetMod field is set.
     */
    @java.lang.Override
    public boolean hasNetSetMod() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 netSetMod = 3;</code>
     * @return The netSetMod.
     */
    @java.lang.Override
    public int getNetSetMod() {
      return netSetMod_;
    }

    public static final int NETSETSTATE_FIELD_NUMBER = 5;
    private int netSetState_;
    /**
     * <code>optional int32 netSetState = 5;</code>
     * @return Whether the netSetState field is set.
     */
    @java.lang.Override
    public boolean hasNetSetState() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 netSetState = 5;</code>
     * @return The netSetState.
     */
    @java.lang.Override
    public int getNetSetState() {
      return netSetState_;
    }

    public static final int NETSETTIME_FIELD_NUMBER = 4;
    private int netSetTime_;
    /**
     * <code>optional int32 netSetTime = 4;</code>
     * @return Whether the netSetTime field is set.
     */
    @java.lang.Override
    public boolean hasNetSetTime() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int32 netSetTime = 4;</code>
     * @return The netSetTime.
     */
    @java.lang.Override
    public int getNetSetTime() {
      return netSetTime_;
    }

    public static final int NETWORKMOD_FIELD_NUMBER = 6;
    private int netWorkMod_;
    /**
     * <code>optional int32 netWorkMod = 6;</code>
     * @return Whether the netWorkMod field is set.
     */
    @java.lang.Override
    public boolean hasNetWorkMod() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional int32 netWorkMod = 6;</code>
     * @return The netWorkMod.
     */
    @java.lang.Override
    public int getNetWorkMod() {
      return netWorkMod_;
    }

    public static final int NETWORKSTATE_FIELD_NUMBER = 9;
    private int netWorkState_;
    /**
     * <code>optional int32 netWorkState = 9;</code>
     * @return Whether the netWorkState field is set.
     */
    @java.lang.Override
    public boolean hasNetWorkState() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional int32 netWorkState = 9;</code>
     * @return The netWorkState.
     */
    @java.lang.Override
    public int getNetWorkState() {
      return netWorkState_;
    }

    public static final int NETWORKTIME_FIELD_NUMBER = 7;
    private int netWorkTime_;
    /**
     * <code>optional int32 netWorkTime = 7;</code>
     * @return Whether the netWorkTime field is set.
     */
    @java.lang.Override
    public boolean hasNetWorkTime() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional int32 netWorkTime = 7;</code>
     * @return The netWorkTime.
     */
    @java.lang.Override
    public int getNetWorkTime() {
      return netWorkTime_;
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private int time_;
    /**
     * <code>optional int32 time = 2;</code>
     * @return Whether the time field is set.
     */
    @java.lang.Override
    public boolean hasTime() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional int32 time = 2;</code>
     * @return The time.
     */
    @java.lang.Override
    public int getTime() {
      return time_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDtuSn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBytes(1, dtuSn_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        output.writeInt32(2, time_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(3, netSetMod_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(4, netSetTime_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, netSetState_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt32(6, netWorkMod_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeInt32(7, netWorkTime_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(8, csq_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeInt32(9, netWorkState_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(10, apSetState_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, dtuSn_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, time_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, netSetMod_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, netSetTime_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, netSetState_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, netWorkMod_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, netWorkTime_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, csq_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, netWorkState_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, apSetState_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq)) {
        return super.equals(obj);
      }
      com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq other = (com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq) obj;

      if (hasApSetState() != other.hasApSetState()) return false;
      if (hasApSetState()) {
        if (getApSetState()
            != other.getApSetState()) return false;
      }
      if (hasCsq() != other.hasCsq()) return false;
      if (hasCsq()) {
        if (getCsq()
            != other.getCsq()) return false;
      }
      if (hasDtuSn() != other.hasDtuSn()) return false;
      if (hasDtuSn()) {
        if (!getDtuSn()
            .equals(other.getDtuSn())) return false;
      }
      if (hasNetSetMod() != other.hasNetSetMod()) return false;
      if (hasNetSetMod()) {
        if (getNetSetMod()
            != other.getNetSetMod()) return false;
      }
      if (hasNetSetState() != other.hasNetSetState()) return false;
      if (hasNetSetState()) {
        if (getNetSetState()
            != other.getNetSetState()) return false;
      }
      if (hasNetSetTime() != other.hasNetSetTime()) return false;
      if (hasNetSetTime()) {
        if (getNetSetTime()
            != other.getNetSetTime()) return false;
      }
      if (hasNetWorkMod() != other.hasNetWorkMod()) return false;
      if (hasNetWorkMod()) {
        if (getNetWorkMod()
            != other.getNetWorkMod()) return false;
      }
      if (hasNetWorkState() != other.hasNetWorkState()) return false;
      if (hasNetWorkState()) {
        if (getNetWorkState()
            != other.getNetWorkState()) return false;
      }
      if (hasNetWorkTime() != other.hasNetWorkTime()) return false;
      if (hasNetWorkTime()) {
        if (getNetWorkTime()
            != other.getNetWorkTime()) return false;
      }
      if (hasTime() != other.hasTime()) return false;
      if (hasTime()) {
        if (getTime()
            != other.getTime()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasApSetState()) {
        hash = (37 * hash) + APSETSTATE_FIELD_NUMBER;
        hash = (53 * hash) + getApSetState();
      }
      if (hasCsq()) {
        hash = (37 * hash) + CSQ_FIELD_NUMBER;
        hash = (53 * hash) + getCsq();
      }
      if (hasDtuSn()) {
        hash = (37 * hash) + DTUSN_FIELD_NUMBER;
        hash = (53 * hash) + getDtuSn().hashCode();
      }
      if (hasNetSetMod()) {
        hash = (37 * hash) + NETSETMOD_FIELD_NUMBER;
        hash = (53 * hash) + getNetSetMod();
      }
      if (hasNetSetState()) {
        hash = (37 * hash) + NETSETSTATE_FIELD_NUMBER;
        hash = (53 * hash) + getNetSetState();
      }
      if (hasNetSetTime()) {
        hash = (37 * hash) + NETSETTIME_FIELD_NUMBER;
        hash = (53 * hash) + getNetSetTime();
      }
      if (hasNetWorkMod()) {
        hash = (37 * hash) + NETWORKMOD_FIELD_NUMBER;
        hash = (53 * hash) + getNetWorkMod();
      }
      if (hasNetWorkState()) {
        hash = (37 * hash) + NETWORKSTATE_FIELD_NUMBER;
        hash = (53 * hash) + getNetWorkState();
      }
      if (hasNetWorkTime()) {
        hash = (37 * hash) + NETWORKTIME_FIELD_NUMBER;
        hash = (53 * hash) + getNetWorkTime();
      }
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hoymiles.NetworkInfoReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hoymiles.NetworkInfoReq)
        com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hoymiles.infrastructure.protos.NetworkInfo.internal_static_hoymiles_NetworkInfoReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hoymiles.infrastructure.protos.NetworkInfo.internal_static_hoymiles_NetworkInfoReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq.class, com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq.Builder.class);
      }

      // Construct using com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        apSetState_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        csq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        dtuSn_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        netSetMod_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        netSetState_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        netSetTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        netWorkMod_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        netWorkState_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        netWorkTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        time_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hoymiles.infrastructure.protos.NetworkInfo.internal_static_hoymiles_NetworkInfoReq_descriptor;
      }

      @java.lang.Override
      public com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq getDefaultInstanceForType() {
        return com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq build() {
        com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq buildPartial() {
        com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq result = new com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.apSetState_ = apSetState_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.csq_ = csq_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dtuSn_ = dtuSn_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.netSetMod_ = netSetMod_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.netSetState_ = netSetState_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.netSetTime_ = netSetTime_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.netWorkMod_ = netWorkMod_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.netWorkState_ = netWorkState_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.netWorkTime_ = netWorkTime_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.time_ = time_;
          to_bitField0_ |= 0x00000200;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq) {
          return mergeFrom((com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq other) {
        if (other == com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq.getDefaultInstance()) return this;
        if (other.hasApSetState()) {
          setApSetState(other.getApSetState());
        }
        if (other.hasCsq()) {
          setCsq(other.getCsq());
        }
        if (other.hasDtuSn()) {
          setDtuSn(other.getDtuSn());
        }
        if (other.hasNetSetMod()) {
          setNetSetMod(other.getNetSetMod());
        }
        if (other.hasNetSetState()) {
          setNetSetState(other.getNetSetState());
        }
        if (other.hasNetSetTime()) {
          setNetSetTime(other.getNetSetTime());
        }
        if (other.hasNetWorkMod()) {
          setNetWorkMod(other.getNetWorkMod());
        }
        if (other.hasNetWorkState()) {
          setNetWorkState(other.getNetWorkState());
        }
        if (other.hasNetWorkTime()) {
          setNetWorkTime(other.getNetWorkTime());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasDtuSn()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int apSetState_ ;
      /**
       * <code>optional int32 apSetState = 10;</code>
       * @return Whether the apSetState field is set.
       */
      @java.lang.Override
      public boolean hasApSetState() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 apSetState = 10;</code>
       * @return The apSetState.
       */
      @java.lang.Override
      public int getApSetState() {
        return apSetState_;
      }
      /**
       * <code>optional int32 apSetState = 10;</code>
       * @param value The apSetState to set.
       * @return This builder for chaining.
       */
      public Builder setApSetState(int value) {
        bitField0_ |= 0x00000001;
        apSetState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 apSetState = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearApSetState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        apSetState_ = 0;
        onChanged();
        return this;
      }

      private int csq_ ;
      /**
       * <code>optional int32 csq = 8;</code>
       * @return Whether the csq field is set.
       */
      @java.lang.Override
      public boolean hasCsq() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 csq = 8;</code>
       * @return The csq.
       */
      @java.lang.Override
      public int getCsq() {
        return csq_;
      }
      /**
       * <code>optional int32 csq = 8;</code>
       * @param value The csq to set.
       * @return This builder for chaining.
       */
      public Builder setCsq(int value) {
        bitField0_ |= 0x00000002;
        csq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 csq = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearCsq() {
        bitField0_ = (bitField0_ & ~0x00000002);
        csq_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString dtuSn_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes dtuSn = 1;</code>
       * @return Whether the dtuSn field is set.
       */
      @java.lang.Override
      public boolean hasDtuSn() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required bytes dtuSn = 1;</code>
       * @return The dtuSn.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getDtuSn() {
        return dtuSn_;
      }
      /**
       * <code>required bytes dtuSn = 1;</code>
       * @param value The dtuSn to set.
       * @return This builder for chaining.
       */
      public Builder setDtuSn(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dtuSn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes dtuSn = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDtuSn() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dtuSn_ = getDefaultInstance().getDtuSn();
        onChanged();
        return this;
      }

      private int netSetMod_ ;
      /**
       * <code>optional int32 netSetMod = 3;</code>
       * @return Whether the netSetMod field is set.
       */
      @java.lang.Override
      public boolean hasNetSetMod() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 netSetMod = 3;</code>
       * @return The netSetMod.
       */
      @java.lang.Override
      public int getNetSetMod() {
        return netSetMod_;
      }
      /**
       * <code>optional int32 netSetMod = 3;</code>
       * @param value The netSetMod to set.
       * @return This builder for chaining.
       */
      public Builder setNetSetMod(int value) {
        bitField0_ |= 0x00000008;
        netSetMod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 netSetMod = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNetSetMod() {
        bitField0_ = (bitField0_ & ~0x00000008);
        netSetMod_ = 0;
        onChanged();
        return this;
      }

      private int netSetState_ ;
      /**
       * <code>optional int32 netSetState = 5;</code>
       * @return Whether the netSetState field is set.
       */
      @java.lang.Override
      public boolean hasNetSetState() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 netSetState = 5;</code>
       * @return The netSetState.
       */
      @java.lang.Override
      public int getNetSetState() {
        return netSetState_;
      }
      /**
       * <code>optional int32 netSetState = 5;</code>
       * @param value The netSetState to set.
       * @return This builder for chaining.
       */
      public Builder setNetSetState(int value) {
        bitField0_ |= 0x00000010;
        netSetState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 netSetState = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearNetSetState() {
        bitField0_ = (bitField0_ & ~0x00000010);
        netSetState_ = 0;
        onChanged();
        return this;
      }

      private int netSetTime_ ;
      /**
       * <code>optional int32 netSetTime = 4;</code>
       * @return Whether the netSetTime field is set.
       */
      @java.lang.Override
      public boolean hasNetSetTime() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional int32 netSetTime = 4;</code>
       * @return The netSetTime.
       */
      @java.lang.Override
      public int getNetSetTime() {
        return netSetTime_;
      }
      /**
       * <code>optional int32 netSetTime = 4;</code>
       * @param value The netSetTime to set.
       * @return This builder for chaining.
       */
      public Builder setNetSetTime(int value) {
        bitField0_ |= 0x00000020;
        netSetTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 netSetTime = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNetSetTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        netSetTime_ = 0;
        onChanged();
        return this;
      }

      private int netWorkMod_ ;
      /**
       * <code>optional int32 netWorkMod = 6;</code>
       * @return Whether the netWorkMod field is set.
       */
      @java.lang.Override
      public boolean hasNetWorkMod() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional int32 netWorkMod = 6;</code>
       * @return The netWorkMod.
       */
      @java.lang.Override
      public int getNetWorkMod() {
        return netWorkMod_;
      }
      /**
       * <code>optional int32 netWorkMod = 6;</code>
       * @param value The netWorkMod to set.
       * @return This builder for chaining.
       */
      public Builder setNetWorkMod(int value) {
        bitField0_ |= 0x00000040;
        netWorkMod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 netWorkMod = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearNetWorkMod() {
        bitField0_ = (bitField0_ & ~0x00000040);
        netWorkMod_ = 0;
        onChanged();
        return this;
      }

      private int netWorkState_ ;
      /**
       * <code>optional int32 netWorkState = 9;</code>
       * @return Whether the netWorkState field is set.
       */
      @java.lang.Override
      public boolean hasNetWorkState() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional int32 netWorkState = 9;</code>
       * @return The netWorkState.
       */
      @java.lang.Override
      public int getNetWorkState() {
        return netWorkState_;
      }
      /**
       * <code>optional int32 netWorkState = 9;</code>
       * @param value The netWorkState to set.
       * @return This builder for chaining.
       */
      public Builder setNetWorkState(int value) {
        bitField0_ |= 0x00000080;
        netWorkState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 netWorkState = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearNetWorkState() {
        bitField0_ = (bitField0_ & ~0x00000080);
        netWorkState_ = 0;
        onChanged();
        return this;
      }

      private int netWorkTime_ ;
      /**
       * <code>optional int32 netWorkTime = 7;</code>
       * @return Whether the netWorkTime field is set.
       */
      @java.lang.Override
      public boolean hasNetWorkTime() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional int32 netWorkTime = 7;</code>
       * @return The netWorkTime.
       */
      @java.lang.Override
      public int getNetWorkTime() {
        return netWorkTime_;
      }
      /**
       * <code>optional int32 netWorkTime = 7;</code>
       * @param value The netWorkTime to set.
       * @return This builder for chaining.
       */
      public Builder setNetWorkTime(int value) {
        bitField0_ |= 0x00000100;
        netWorkTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 netWorkTime = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearNetWorkTime() {
        bitField0_ = (bitField0_ & ~0x00000100);
        netWorkTime_ = 0;
        onChanged();
        return this;
      }

      private int time_ ;
      /**
       * <code>optional int32 time = 2;</code>
       * @return Whether the time field is set.
       */
      @java.lang.Override
      public boolean hasTime() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>optional int32 time = 2;</code>
       * @return The time.
       */
      @java.lang.Override
      public int getTime() {
        return time_;
      }
      /**
       * <code>optional int32 time = 2;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(int value) {
        bitField0_ |= 0x00000200;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000200);
        time_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:hoymiles.NetworkInfoReq)
    }

    // @@protoc_insertion_point(class_scope:hoymiles.NetworkInfoReq)
    private static final com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq();
    }

    public static com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NetworkInfoReq>
        PARSER = new com.google.protobuf.AbstractParser<NetworkInfoReq>() {
      @java.lang.Override
      public NetworkInfoReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetworkInfoReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NetworkInfoReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetworkInfoReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hoymiles.infrastructure.protos.NetworkInfo.NetworkInfoReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hoymiles_NetworkInfoRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hoymiles_NetworkInfoRes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hoymiles_NetworkInfoReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hoymiles_NetworkInfoReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*src/main/resources/proto/NetworkInfo.p" +
      "roto\022\010hoymiles\".\n\016NetworkInfoRes\022\016\n\006offs" +
      "et\030\001 \002(\005\022\014\n\004time\030\002 \002(\005\"\311\001\n\016NetworkInfoRe" +
      "q\022\022\n\napSetState\030\n \001(\005\022\013\n\003csq\030\010 \001(\005\022\r\n\005dt" +
      "uSn\030\001 \002(\014\022\021\n\tnetSetMod\030\003 \001(\005\022\023\n\013netSetSt" +
      "ate\030\005 \001(\005\022\022\n\nnetSetTime\030\004 \001(\005\022\022\n\nnetWork" +
      "Mod\030\006 \001(\005\022\024\n\014netWorkState\030\t \001(\005\022\023\n\013netWo" +
      "rkTime\030\007 \001(\005\022\014\n\004time\030\002 \001(\005B3\n\"com.hoymil" +
      "es.infrastructure.protosB\013NetworkInfoP\000"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_hoymiles_NetworkInfoRes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hoymiles_NetworkInfoRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hoymiles_NetworkInfoRes_descriptor,
        new java.lang.String[] { "Offset", "Time", });
    internal_static_hoymiles_NetworkInfoReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hoymiles_NetworkInfoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hoymiles_NetworkInfoReq_descriptor,
        new java.lang.String[] { "ApSetState", "Csq", "DtuSn", "NetSetMod", "NetSetState", "NetSetTime", "NetWorkMod", "NetWorkState", "NetWorkTime", "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
